sudo: false
language: python
# Stick to a known-good version of tox, just in case:
install: pip install tox==1.9.2
# Command to run tests. 3.1 is missing on Travis.
script: tox --skip-missing-interpreters
